import Image from 'next/image'
import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Practice Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className='py-12 flex justify-around'>
            <figure>
              <Image
                className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert aspect-ratio"
                src="/next.svg"
                alt="Next.js Logo"
                width={115}
                height={0}
                priority
              />
            </figure>
            <ul className='flex gap-11'>
              <li><Link href="/">Home</Link></li>
              <li><Link href="/register">Register</Link></li>
            </ul>
          </nav>
        </header>
        {children}
        <footer className='flex justify-center py-24'>
          All rights reserved @next-practice-project
        </footer>
      </body>
    </html>
  )
}
